behaviors:
  MLMazeAgent:
    trainer_type: ppo
    curriculum:
      maze_size:
        - name: MazeSizeCurriculum
          completion_criteria:
            measure: progress
            thresholds: [0.3, 0.6]
            min_lesson_length: 10000
          parameters:
            maze_size: 
              - 5.0
              - 8.0
              - 11.0