behaviors:
  MLMazeAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 65536  
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.15
      lambd: 0.9
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      memory:
        memory_size: 512
        sequence_length: 64
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:  # Add this section
        strength: 0.1
        gamma: 0.99
        encoding_size: 256
        learning_rate: 1e-4
    max_steps: 5e6
    time_horizon: 128
    summary_freq: 5000

environment_parameters:
  maze_size:
    curriculum:
      - name: SmallMaze
        completion_criteria:
          measure: progress
          behavior: MLMazeAgent
          signal_smoothing: true
          min_lesson_length: 50000
          threshold: 0.8
        value: 5.0

      - name: MediumMaze
        completion_criteria:
          measure: progress
          behavior: MLMazeAgent
          signal_smoothing: true
          min_lesson_length: 60000
          threshold: 0.8
        value: 7.0

      - name: LargeMaze
        # no completion criteria for last lesson
        value: 10.0